New Workflow for Google Apigee
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #101
Opened 2022-05-10 17:42 UTC by KgosiTshepo

A workflow to collect audit events from Google Apigee.

2022-05-10 18:29 UTC, ChrisCollinsIBM requested changes
Looks great overall, just looking for some additional information and clarification on a few items. 

Thanks for the submission!

2022-05-10 18:29 UTC, ChrisCollinsIBM commented on Community Developed/Google Apigee/Google-Apigee-Parameter-Values.xml
> +    <Value name="base64EncodedCredentials" value="" />
The readme.md doesn't mention where these credentials should come from and what precisely to put into base64 to include here.

I checked the referenced page in the readme.md https://docs-edgeapis.apigee.io/docs/audits/1/routes/audits/organizations/%7Borg_name%7D/get and I didn't find any additional information there either.

It would be good to include some details in the readme.md on where to get the credentials what string exactly should be encoded to base64

Looking here https://docs.apigee.com/api-platform/reference/policies/basic-authentication-policy it seems to be `user:password` then converted to base64 as you're already handling adding the "Authorization" and "Basic _____" portion of the request format.

2022-05-22 00:01 UTC, KgosiTshepo commented
@ChrisCollinsIBM  I have made the changes , please review 👀

2022-07-06 16:47 UTC, ChrisCollinsIBM reviewed
My apologies for not catching this the first time, but I think the usability of this workflow would be greatly enhanced by allowing username/password instead of requiring the end user to provide the base64 blob from `username:password` being base64 encoded.

If you don't want to change it that's certainly fine, but I think it would be a large usability improvement.

2022-07-06 16:47 UTC, ChrisCollinsIBM commented on Community Developed/Google Apigee/ReadMe.md
> +This workflow uses a Basic Authentication policy which takes a `username` and `password`, base64 encodes them. The resulting value is assigned to an HTTP Authorization request header.
Lots of detail in the ReadMe which is great, the only thing I think is missing is as an end user where do I get the information to put into the `base64EncodedString` parameter (which used to be called credentials).

Personally I know that for basic auth it's `username:password` then base64 encoding, but I don't see in here how the end user is supposed to know that.

Have you considered having them provide the username and password instead and then using the `<BasicAuthentication>` method we provide for `<CallEndpoint>`?

Example from https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/c6ba900dc9284c35415b164f96fb293094e4c0fd/Community%20Developed/ServiceNow/ServiceNow-Workflow.xml#L30

```
  <CallEndpoint url="https://${/host}/urlparamters" method="GET" savePath="/get_logs" >
            <BasicAuthentication username="${/Integration_ID}" password="${/Password}" />
            <QueryParameter name="from_time" value="${/fromTime}" omitIfEmpty="true" /> 
            <QueryParameter name="to_time" value="${/toTime}" omitIfEmpty="true" />
        </CallEndpoint>
```

2022-07-06 16:47 UTC, ChrisCollinsIBM commented on Community Developed/Google Apigee/Google-Apigee-Workflow.xml
> +            <RequestHeader name="Authorization" value="Basic ${/base64EncodedString}" />
As I mention in another comment, `<CallEndpoint>` supports a `<BasicAuthentication>` tag that will do this for you, and allow your customer to input a username and password as parameters, lessening the chance they mess up in constructing the `username:password` base64 blob.

2022-10-25 19:57 UTC, ChrisCollinsIBM commented
Changes have been requested prior to merging this workflow, please let me know if you have any questions or require any assistance.

Thanks!

2024-07-24 18:25 UTC, merged

2024-07-24 18:25 UTC, ChrisCollinsIBM commented
Going to merge this one in since the required changes weren't critical.