Add Nozomi Networks Vantage Workflow #105
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #106
Opened 2022-06-09 07:16 UTC by nicoloereni

2022-07-06 16:32 UTC, ChrisCollinsIBM requested changes
Great submission overall! 

I added a few comments for some items that I think could use some changes and some more clarity.

2022-07-06 16:32 UTC, ChrisCollinsIBM commented on Community Developed/NozomiNetworks/Vantage/NN-Vantage-Workflow.xml
> +-->
This instruction block probably should be moved to the Workflow Parameters as that's where the value need to be input.

2022-07-06 16:32 UTC, ChrisCollinsIBM commented on Community Developed/NozomiNetworks/Vantage/NN-Vantage-Workflow.xml
> +    <Initialize path="/bookmark_assets" value="0" />
If `bookmark` and `bookmark_assets` are initialized with `0`, do you end up pulling ALL available data back to the beginning of time (or however far the API lets you go back) on the very first run?

If you have you considered initializing the value with an offset from the current time? Many of the workflows you will see follow this pattern but using something like  

`<Initialize path="/auth_logs/bookmark" value="${time() - 3600000}" />`
This is a 1 hour offset from https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/master/Community%20Developed/Duo/Duo-Security-Workflow.xml#L39

Wiz has a good example as well: https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/master/Community%20Developed/Wiz/Wiz-Workflow.xml#L15

2022-07-06 16:32 UTC, ChrisCollinsIBM commented on Community Developed/NozomiNetworks/Vantage/README.md
> +`"` to  `&quot;`
I appreciate why you included these special characters, if the access token has any of these characters in them then it will have to escaped with the list below.  If that's happening often you might want to cite this example specifically and give an example key_token where this had to happen to help them configure but ultimately as you mention it's required for ANY string field in XML.

2022-07-07 08:57 UTC, nicoloereni commented on Community Developed/NozomiNetworks/Vantage/README.md
> +`"` to  `&quot;`
I don't think this happen often, the key_token, key_name and host never contain special characters. Only organization name could have special characters.

2022-07-07 09:16 UTC, nicoloereni commented on Community Developed/NozomiNetworks/Vantage/NN-Vantage-Workflow.xml
> +    <Initialize path="/bookmark_assets" value="0" />
For the _bookmark_assets_ it's ok to take all the assets and it's the use case I've always seen for our customers.

For the _bookmark_ could be interesting to get alerts from a fixed time.
I add a comment in case a customer wants to change this behavior.

2022-07-07 10:20 UTC, closed without merging

2022-07-07 10:20 UTC, nicoloereni commented
I did a mess, I'll open a new one