Zoom Workflow for /report/activities endpoint
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #114
Opened 2022-07-07 11:19 UTC by xkimopro

Hello team. I would like to edit the Workflow for zoom.  The version uploaded can be deployed in production and fetch all sign ins and sign outs of a business zoom account through a JWT application. Special thanks to @ChrisCollinsIBM  for uploading the initial POC workflow.

2022-07-07 14:36 UTC, ChrisCollinsIBM requested changes
Really great update to an in-demand workflow, thanks @xkimopro !

I've added some comments, one which needs to be done for sure (the initial date) and a couple of others for your consideration.

2022-07-07 15:18 UTC, xkimopro commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <Initialize path="/last_event_time" value="${/initial_timestamp}"></Initialize>
Thats correct. Indeed hardcoding a timestamp into a variable that is used only once isn't a good practice. I will change it on the next request

2022-07-07 15:23 UTC, xkimopro commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <While condition="/get_events/body/next_page_token != ''">
Thats correct also. It could be removed by implementing a DoWhile. The reason i did that was to avoid the first_run logic i wanted the script to be agnostic of its time being run (1st ,2nd etc...) and i also didnt know how the default JPath of /token would behave when not initialized. I will propably fix that when logical operators will be implemented. Thank you!

2022-07-07 15:31 UTC, ChrisCollinsIBM commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <While condition="/get_events/body/next_page_token != ''">
Logical operators MIGHT actually already work. And with the <DoWhile> setup you really don't need them based on the second suggestion.

By avoiding first_run logic in the loop, you're currently duplicating a ton of stuff which is inherently more risky than troubleshooting first_run logic.

2022-07-07 17:07 UTC, xkimopro commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <While condition="/get_events/body/next_page_token != ''">
Okay i will implement the second snippet , change the variable definition of last_event_time and retest my code locally. Thanks a lot for the feedback.

2022-08-04 07:53 UTC, xkimopro commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <While condition="/get_events/body/next_page_token != ''">
Hello. Did you look at the changes made?  Do you have any feedback for the updated version?

2022-10-26 12:47 UTC, ChrisCollinsIBM commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <Initialize path="/bookmark" value="${time() - (60000 * 60 * 24 * 10)}"></Initialize>
You don't need to change it, but for these you can just terminate the tag inline.
```<Initialize path="/bookmark" value="${time() - (60000 * 60 * 24 * 10)}" />```

2022-10-26 13:06 UTC, xkimopro commented on IBM Proof Of Concept/Zoom/Zoom-Workflow.xml
> +        <Initialize path="/bookmark" value="${time() - (60000 * 60 * 24 * 10)}"></Initialize>
Hello @Chris nice hearing from you again. I ve converted every non self enclosing tag to a self enclosing one where possible. Check my latest commit! 
Thanks

2023-05-29 15:31 UTC, ChrisCollinsIBM commented
Thanks for the updates! Sorry for the delay in the merge.

2023-05-29 15:31 UTC, merged