Zero Networks v1
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #118
Opened 2022-07-14 17:48 UTC by dicolanl

We have created this workflow to ingest Zero Networks Audit log.

We tested this with a customer and its working.

2022-10-25 18:23 UTC, ChrisCollinsIBM commented on Community Developed/ZeroNetworks/ReadMe.md
> +5. On the Select a Log Source Type page, _Select a Log Source Type (Universal DSM)_ and click _Select Protocol Type_.
Do you have a custom DSM published to go along with this? Bringing it into Universal DSM without any additional context will log the events, but no parsing will be done.

That doesn't need to done to merge the workflow here, but once you do have something available either on the X-Force Exchange or your own website you should definitely link to it here.

2022-10-25 18:25 UTC, ChrisCollinsIBM commented on Community Developed/ZeroNetworks/ReadMe.md
> +2. host : The portal url
```suggestion
2. host : The portal hostname
```

I'd suggest using the term `hostname`, a URL is slightly different and includes a path and optionally a protocol (https:// for example)

2022-10-25 18:34 UTC, ChrisCollinsIBM commented on Community Developed/ZeroNetworks/ZeroNetworks-Workflow.xml
> +            <SSLConfiguration allowUntrustedServerCertificate="true" />
If your solution is SaaS and usually has a certificate issued to it by a verified issuer (DigiCert, LetsEncrypt, etc) then I would not recommend hardcoding this option. 

If users need to use it in situations where an on-prem version of the product may have a self-signed or otherwise problematic certificate then they choose the option in the UI when configuring the workflow and CallEndpoint will handle the unstrusted there.

![image](https://user-images.githubusercontent.com/931160/197854162-f9e10f33-810c-43ea-8bf2-fe9ee4a009ae.png)

2022-10-25 18:36 UTC, ChrisCollinsIBM requested changes
Great submission, the main thing to resolve is the hardcoded `allowUnstrustedCertficates` option.

Thanks!

2022-10-25 19:41 UTC, ChrisCollinsIBM requested changes
Thanks for the submission, a bit of the feedback are just suggestions and not mandatory, but the allowUntrusted hardcoding definitely needs to be addressed. 

Thanks!

2023-05-29 15:06 UTC, ChrisCollinsIBM commented
Just wanted to follow up to see if you have any questions or comments on the requested changes.

Thanks!

2023-05-29 22:35 UTC, dicolanl commented
@ChrisCollinsIBM ill fix this week. Was working a dsm which has now been reviewed too.

2024-07-24 18:26 UTC, ChrisCollinsIBM approved these changes

2024-07-24 18:26 UTC, merged