Add GoogleWorkspaceAlertCenter workflow #137
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #142
Opened 2022-11-01 14:20 UTC by paulofdantas

Hi! I am a QRadar on Cloud customer so I don't have access to server CLI to use the workflow validation tool and generate the sample, but I attached some screenshots to fulfill the workflow samples requirements.

Best regards,

Paulo Dantas

![Screenshot 2022-11-01 at 09 49 04](https://user-images.githubusercontent.com/20095130/199236919-aab6de0f-48c2-4f84-90a0-acf3772387c4.png)

![Screenshot 2022-11-01 at 09 46 45](https://user-images.githubusercontent.com/20095130/199236934-a1db44de-218a-418f-b667-cf3265e0a12d.png)

2022-11-02 13:38 UTC, ChrisCollinsIBM requested changes

2022-11-02 13:38 UTC, ChrisCollinsIBM commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +                <QueryParameter name="filter"   value='(createTime >= &quot;${/bookmark}&quot;)' omitIfEmpty="true" />
```suggestion
                <QueryParameter name="filter"   value='(createTime >= &quot;${/bookmark}&quot;)' />
```

`omitIfEmpty="true"` wouldn't be necessary here, since you're providing a partial value (only the bookmark is dynamic) it will never be empty.

2022-11-02 13:38 UTC, ChrisCollinsIBM commented on Google Workspace Alert Center/README.md
> +IMPORTANT: Copy the entire private key from your service account JSON Key file replacing all the '\n' with line breaks and encode the key using Base64 before paste it in the 'GoogleWorkspaceAlertCent
Here's a possible helper you can include. This works on a QRadar box and should work anywhere with a similar grep/awk installation.

`grep -o -e "-----BEGIN PRIVATE KEY-----[^\"]\+" service_account_credentials.json | awk  '{gsub("\\\\n","\n")};1' | base64 -w0`

grep finds the line, -o covers only the match, awk replaces the newlines, and the -w0 on base64 disables line wrapping.

2022-11-02 13:38 UTC, ChrisCollinsIBM commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +        <Parameter name="user_email" label="Client ID" required="true" />
These fields are both labelled `Client ID`

2022-11-03 01:45 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +        <TCPConnectionTest host="https://alertcenter.googleapis.com" />
Hi @ChrisCollinsIBM , I did this new pull request just to properly use the sign off requirement. I did those changes you suggested creating a new variable to API Host and the tests successfully passed.

2022-11-03 01:47 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +        <CallEndpoint url="https://alertcenter.googleapis.com/v1beta1/alerts/" method="GET" savePath="/get_logs" >
I changed that part in the code and I think it's better now, making just one call and checking _'if there events then post events and update the bookmark'_ . Thank you for your suggestion.

2022-11-03 01:50 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +            <CallEndpoint url="https://alertcenter.googleapis.com/v1beta1/alerts/" method="GET" savePath="/get_logs" >
So, once my purpose is to catch only the new alerts from alert center and security center I didn't implemented this feature, but It's a great idea if I need to get some events that happened in the past. Now I change the query to call the API for 24 hours before the current API call.

2022-11-03 01:52 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +                <QueryParameter name="filter"   value='(createTime >= &quot;${/bookmark}&quot;)' omitIfEmpty="true" />
Solved this line already in the new commit. Thank you for explanation about this.

2022-11-03 01:53 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +        <Parameter name="user_email" label="Client ID" required="true" />
Yes! Thank you for warning me, I fixed that.

2022-11-03 01:59 UTC, paulofdantas commented on Google Workspace Alert Center/README.md
> +IMPORTANT: Copy the entire private key from your service account JSON Key file replacing all the '\n' with line breaks and encode the key using Base64 before paste it in the 'GoogleWorkspaceAlertCent
Amazing! It will be very helpful to properly formatting the private key, added this to the README.md

2022-11-03 03:07 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +            <CallEndpoint url="https://alertcenter.googleapis.com/v1beta1/alerts/" method="GET" savePath="/get_logs" >
After my last changes in the Workflow this error started to happen:

![image](https://user-images.githubusercontent.com/20095130/199640401-5a5c0fc7-7a0b-4861-9b3c-f01a54db8829.png)

Is the new event timestamp to query the API from the last event.

2022-11-03 14:17 UTC, paulofdantas commented on Google Workspace Alert Center/GoogleWorkspaceAlertCenter-Workflow.xml
> +        <CallEndpoint url="https://alertcenter.googleapis.com/v1beta1/alerts/" method="GET" savePath="/get_logs" >
Hey @ChrisCollinsIBM ! I think I found the solution, I will update the workflow and commit the new changes.

2024-05-30 16:48 UTC, ChrisCollinsIBM approved these changes

2024-05-30 16:48 UTC, merged

2024-05-30 19:19 UTC, paulofdantas commented
Thank you Chris! Appreciate that.