Add XM Cyber workflow
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #157
Opened 2023-01-26 10:00 UTC by herrmannben

Hi,

I've created a workflow for XM Cyber and I wanted to add it to [IBM-QRadar-Universal-Cloud-REST-API](https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API).

Thanks,
Benjamin

2023-04-18 12:59 UTC, ChrisCollinsIBM requested changes
Thanks for the submissions and apologies in the delay on the review.

I have a few questions on the overall function of the workflow as I've outlined in the review. It seems like there would be no problem getting the data you're looking for, but I don't see how it synchronizes between runs to ensure only "new" items show up on each run. So if you can provide some commentary on that it would be appreciated.

Thanks for the submission.

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Parameter-Values.xml
> +	<Value name="api_host" value="" />
It would be nice to have a Readme.md included to assist users with where to get the `api_host` and `api_key` with a brief description of the integration. 

That's not 100% required, but in absence of that some XML comments to remind a user that "api_host" is just the hostname (not including https:// or any path info) to help with configuration as many users won't read down into the workflow to see.

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +				<QueryParameter  name="timeId" value="timeAgo_days_30" />
So it looks like on a first run, it makes a query to get 30 days worth of data. I'm guessing `timeAgo_days_30` is a parameter XM Cyber uses to calculate 30 days ago since this isn't anything from the workflow.

My followup question will be on line 51

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/newAssetsComrpomised" method="GET" savePath="/newAssetsComrpomised">
If the `first_run` block from line 19 only ever runs the first time, how does this query here find new assets in relation to that one since this query doesn't have any kind of timestamp bound to it?

The API documentation isn't public so I can't actually have a look at this call to see if there's any mention of some type of automatic internal synchronization for "new" items, but in a REST API those types of mechanisms usually don't exist.

More information on this would be helpful to explain.

Also on this API call I noticed the path has `newAssetsComrpomised` instead of `newAssetsCompromised` - since I can't see the API docs I can't confirm if this is correct or not but with compromised misspelled here it would have to match what is in the API. Can you advise if this was intended or not?

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/newAttackTechniques" method="GET" savePath="/newAttackTechniques">
Similar question here as with line 51, where this query doesn't have any time bounds how does it know what is "new" between queries?

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/scenarioGradeDownEvents" method="GET" savePath="/scenarioGradeDownEvents">
Similar question here as with line 51, where this query doesn't have any time bounds how does it know what is "new" between queries?

2023-04-18 12:59 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/scenarioGradeUpEvents" method="GET" savePath="/scenarioGradeUpEvents">
Similar question here as with line 51, where this query doesn't have any time bounds how does it know what is "new" between queries?

2023-04-19 07:24 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +				<QueryParameter  name="timeId" value="timeAgo_days_30" />
Right, the calculation is done on the server side.

2023-04-19 07:29 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/newAssetsComrpomised" method="GET" savePath="/newAssetsComrpomised">
This workflow will run once a day (it is part of the configuration instructions in the docs for installing the Qradar extension).
This rest endpoint is sending the "new" elements that appeared in the last day.
Yes, there is a typo in `newAssetsCompromised ` but this is a typo on the rest api side, and other applications are using it

2023-04-19 07:35 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/newAttackTechniques" method="GET" savePath="/newAttackTechniques">
Similar response as with line 51

2023-04-19 07:35 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/scenarioGradeDownEvents" method="GET" savePath="/scenarioGradeDownEvents">
Similar response as with line 51

2023-04-19 07:35 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Workflow.xml
> +		<CallEndpoint url="https://${/api_host}/api/systemReport/scenarioGradeUpEvents" method="GET" savePath="/scenarioGradeUpEvents">
Similar response as with line 51

2023-04-19 07:37 UTC, herrmannben commented on Community Developed/XM Cyber/XM-Cyber-Parameter-Values.xml
> +	<Value name="api_host" value="" />
The docs available when installing the Qradar extension already includes all of these details (and we will add a link to this repo after the merge). Is it really necessary to copy  these details here?

2023-05-18 16:38 UTC, ChrisCollinsIBM commented on Community Developed/XM Cyber/XM-Cyber-Parameter-Values.xml
> +	<Value name="api_host" value="" />
If you don't want to include details here no problem, for the Readme.md if you just want to link out to your external docs that would be fine too.

Thanks!

2023-05-18 16:52 UTC, ChrisCollinsIBM approved these changes

2023-05-18 16:52 UTC, merged