Crowdstrike Detections
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #158
Opened 2023-02-11 01:15 UTC by theycallmecharlie

Adding a workflow of crowdstrike detections

Get the client and secret: https://www.crowdstrike.com/blog/tech-center/get-access-falcon-apis/

Use this if you have a multi tenant qradar and already a crowdstrike app installed to get events from other tenants with different log sources identifiers

2023-02-27 14:48 UTC, ChrisCollinsIBM requested changes
Thanks for the submission!

Overall this looks like it would be functional with a small number of detections but I have some concerns it might have issues regarding paging in general and as the `while` loop relates to total_events.

Have a look at my comments and let me know what you think.

2023-02-27 14:48 UTC, ChrisCollinsIBM commented on Community Developed/Crowdstrike/crowdstrike.xml
> +        <Set path="/total_detections" value="${count(/get_detection_details/body/resources)}" />
Do you need to rely on the `total_detections` value being correct? Or can you just iterate over the `${/get_detection_details/body/resources[]}` array?

And is `total_detections` based on the number returned by the query? Or the number on the active page? (See the paging question above)

2023-02-27 14:48 UTC, ChrisCollinsIBM commented on Community Developed/Crowdstrike/crowdstrike.xml
> +        <CallEndpoint url="https://${/api_host}/detects/entities/summaries/GET/v1?filter=created_timestamp:>'${/created_timestamp}'" method="POST" savePath="/get_detection_details">
Does this API have paging? And if so how many detections will be returned until you need account for paging?

Most APIs will only return so many rows before you need to page either via a record count offset or some type of paging token.

2023-02-27 14:48 UTC, ChrisCollinsIBM commented on Community Developed/Crowdstrike/crowdstrike.xml
> +        <Set path="/j" value="${/total_detections}" />
The `j` value is only used once, you can probably just reference `${/total_detections}` again on line 34 and remove this.

2023-03-03 17:17 UTC, theycallmecharlie commented on Community Developed/Crowdstrike/crowdstrike.xml
> +        <Set path="/j" value="${/total_detections}" />
Hi chris, I overwrited this structure by the foreach

2023-03-03 17:22 UTC, theycallmecharlie commented on Community Developed/Crowdstrike/crowdstrike.xml
> +        <Set path="/total_detections" value="${count(/get_detection_details/body/resources)}" />
Yes, now the total_detections is being iterated with a foreach estructure
There's no pagination on response.

2023-03-03 17:33 UTC, theycallmecharlie commented
@ChrisCollinsIBM  i commited a update to crowdstrike.xml, what do u think?

2024-07-24 18:27 UTC, ChrisCollinsIBM approved these changes

2024-07-24 18:27 UTC, merged