Add Gem Security workflow #180
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #181
Opened 2023-06-18 12:26 UTC by karinbra

Add Workflow and Workflow parameter values for ingesting notifications from Gem Security

2023-06-22 14:51 UTC, ChrisCollinsIBM commented on Community Developed/Gem/Gem-Workflow-Parameter-Values.xml
> +    <Value name="tokenUrlDomain" value="login.gem.security"/>
Is `tokenUrlDomain`, `apiUrl`, and `audienceUrl` the same for all customers?

If so then they probably should be moved to variables within the workflow itself rather than be in the parameter file.

If they could vary by customer then having them as parameters still makes sense.

2023-06-22 18:43 UTC, ChrisCollinsIBM requested changes
Great submission!

Just looking for some feedback on the input parameters.

2023-06-22 18:46 UTC, ChrisCollinsIBM commented on Community Developed/Gem/Gem-Workflow-Parameter-Values.xml
> +    <Value name="tokenUrlDomain" value="login.gem.security"/>
Usually the things in parameters are things people will have to change for them. If it's the same for everyone usually that'd be a variable in the workflow itself, but if you'd like to leave them in the parameters that's ok, maybe just use an XML comment to note them in the parameters with a "Only change these if advised" type of message and physically space them out from the clientID and secret with a blank line.

2023-06-24 14:19 UTC, karinbra commented on Community Developed/Gem/Gem-Workflow-Parameter-Values.xml
> +    <Value name="tokenUrlDomain" value="login.gem.security"/>
@ChrisCollinsIBM Great suggestions! I've added the comment and separated those values from clientID and secret.

2023-06-24 14:20 UTC, karinbra commented
> Great submission!
> 
> Just looking for some feedback on the input parameters.

Hi Chris! I've added the suggested comments in the parameter values file. What do you think?

2023-06-30 14:46 UTC, ChrisCollinsIBM commented
Looks great, thanks for the small updates and the submission!

2023-06-30 14:46 UTC, ChrisCollinsIBM approved these changes

2023-06-30 14:47 UTC, merged