Add workflows for BeyondTrust Privilege Management Cloud #192
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #198
Opened 2023-08-29 20:05 UTC by jamos-bt

2025-04-24 13:46 UTC, ChrisCollinsIBM requested changes
Very well written and organized overall, thanks for the submission and sorry for the delay!

Please comment and resolve the review notes and let me know if you'd like to address them before merge and we can discuss as needed.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/README.md
> +    - **Log Source Identifier** - It is suggested to initially use a dummy value, then once all configuration is entered and you reach the **Test** step below, the test should return the correct iden
In Schema V1 and V2, `<PostEvent>` and `<PostEvents>` require a `source` attribute which is what drives this slighty complicated behaviour that customers must follow (figuring out what log source identifier to use).

In V2_1 we simplified this for developers and customers by making `source` optional. When a `source` is not specified then ANY Log Source Identifier may be used in the configuration on the QRadar side (which is usually what you want).

Example of referencing the V2_1 schema:
https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/d5f84d39180a3280c8651af4401418f8529c7000/Community%20Developed/Netskope/Netskope-UBA-Alert-Workflow.xml#L3

PostEvents sample without `source`:
https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/d5f84d39180a3280c8651af4401418f8529c7000/Community%20Developed/Netskope/Netskope-UBA-Alert-Workflow.xml#L92

Additionally updating to schema V2_1 brings your workflow into the V2 namespace which is where most new development and bug fixes will occur.

This change isn't REQUIRED to get your merge in, but I think your customer experience would be better without the convoluted Log Source Identifier processes that occur when you have to specify the `source` attribute in V1/V2.

Let me know here if you'd like to merge as-is and address it later, or if you want to make this change beforehand.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ClientEvents-Workflow.xml
> +                <PostEvent path="/event" source="${/hostname}"/>
Check CR comment on the `README.md` around updating to Schema V2_1 to simplify this and omit the `source` tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ClientEvents-Workflow.xml
> +  xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1">
Check CR comment on the README.md around updating to Schema V2_1 to simplify this and omit the source tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ClientEvents-Workflow-Parameter-Values.xml
> +<WorkflowParameterValues xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/WorkflowParameterValues/V1">
Check CR comment on the README.md around updating to Schema V2_1 to simplify this and omit the source tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow-Parameter-Values.xml
> +<WorkflowParameterValues xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/WorkflowParameterValues/V1">
Check CR comment on the README.md around updating to Schema V2_1 to simplify this and omit the source tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +  xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1">
Check CR comment on the README.md around updating to Schema V2_1 to simplify this and omit the source tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +                <PostEvent path="/event" source="${/hostname}"/>
Check CR comment on the README.md around updating to Schema V2_1 to simplify this and omit the source tag.

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +        <Set path="/access_token" value="${/auth_token_response/body/access_token}" />
Anything `<Set>` will be persisted to disk at the end of the run in the state file, since an access token is ultimately a secret when you are finished with it in the workflow you should `<Delete>` the path to ensure it isn't saved and possibly misused.

https://www.ibm.com/docs/en/dsm?topic=actions-delete

2025-04-24 13:46 UTC, ChrisCollinsIBM commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +
This would be a good place to clear the access token as mentioned in a previously comment.

2025-04-24 18:01 UTC, ChrisCollinsIBM commented
Please add DCO signoff as well

https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/pull/198/checks?check_run_id=34400148756

2025-06-13 17:55 UTC, jamos-bt commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +        <Set path="/access_token" value="${/auth_token_response/body/access_token}" />
Done!

2025-06-13 17:55 UTC, jamos-bt commented on Community Developed/BeyondTrust/PM Cloud/BeyondTrust-PMCloud-ActivityAudits-Workflow.xml
> +
Done!

2025-06-13 17:57 UTC, jamos-bt commented
All feedback addressed and the changes tested / confirmed.  Thanks for the pointers @ChrisCollinsIBM!

2025-08-27 15:53 UTC, jamos-bt commented
@ChrisCollinsIBM Just a quick ping here ... we did update workflows with all your suggestions.  Thanks!

2025-09-02 13:15 UTC, ChrisCollinsIBM approved these changes
Looks great, changing over to the 2.1 schema will certainly make it easier for customers to configure.

Thanks for the submission!

2025-09-02 13:16 UTC, merged