Add CyberArk EPM workflow files
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #201
Opened 2023-09-16 16:56 UTC by compostCY

Hello team:
Jawine Westland from your team has QA the app within the last few months. She has posted this in the IBM page already. 
https://exchange.xforce.ibmcloud.com/hub/extension/6f4fd73ae721109d758d6807ba8e404c

She ask me to upload the xml files here by creating a fork and a pull request. I want to put this into the CyberArk EPM folder, but i can't seems to create the folder while uploading. Could you please ensure this is in the CyberArk EPM folder ? Thanks.
==
Use the "Add File" button to upload all your files. Note that to create a folder, you simply include a / in the file name to create (e.g. My Favorite Vendor/MyFavoriteVendor-Workflow.xml).
==
I was not able to create the folder using step above while uploading.

2023-09-18 12:53 UTC, ChrisCollinsIBM requested changes
Thanks for the submission, I added a few comments around default values for parameters as well as some of the timestamps being used to initialize initial collection.

As well, we also need a README.md with a small overview of what the 3 workflows are for, and possibly where the users would configure the access and what level of access is required (standard permissions for example) to help ensure users don't just use an admin user with more permissions than required.

Thank you!

2023-09-18 12:53 UTC, ChrisCollinsIBM commented on CyberArk-EPM-AggregatedPolicy-Workflow.xml
> +        <Initialize path="/epm_policy/bookmark" value="${time() - (60000 * 60 * 24 * 7)}" /> <!-- 1 days prior -->
This one is set to 7 days but in the comments it's indicated that it is 1 day.

2023-09-18 18:05 UTC, compostCY commented on CyberArk-EPM-AdminAudits-Workflow.xml
> +        <Parameter name="username" label="Username" default="johndoe" required="true" />
Thanks Chris:
Got it, sure we can remove it. We can just make it required. As this is my first time coding this, i am following the patterns from others. I model this from from CyberArk Idaptive workflow where they have this as well:
     <Parameter name="username" label="Username" default="siemuser" required="true" />

I am ok removing it if you need to.

2023-09-18 18:06 UTC, compostCY commented on CyberArk-EPM-AggregatedEvents-Workflow.xml
> +        <Initialize path="/epm_event/bookmark" value="${time() - (60000 * 60 * 24 * 1)}" /> <!-- 7 days prior -->
my apology, this should default to 7 days out of the box.

2023-09-18 18:07 UTC, compostCY commented on CyberArk-EPM-AggregatedPolicy-Workflow.xml
> +        <Initialize path="/epm_policy/bookmark" value="${time() - (60000 * 60 * 24 * 7)}" /> <!-- 1 days prior -->
apology, for policy event, it should default to 1 day, as there could be potential many policy record.

2023-09-22 16:36 UTC, ChrisCollinsIBM commented on CyberArk-EPM-AdminAudits-Workflow.xml
> +        <Parameter name="username" label="Username" default="johndoe" required="true" />
You would commit it as a file README.md into the same directory as the workflows.

2023-09-22 16:36 UTC, ChrisCollinsIBM commented on CyberArk-EPM-AggregatedEvents-Workflow.xml
> +        <Initialize path="/epm_event/bookmark" value="${time() - (60000 * 60 * 24 * 1)}" /> <!-- 7 days prior -->
Can you update in the workflow please with a new commit? For this as well as the other one.

2023-09-22 16:37 UTC, ChrisCollinsIBM commented
Hi @compostCY, the review issues are marked as resolved but I don't see another commit with the changes.

Can you please make the updates as well as add the README.md and then I'll get the PR merged in.

2023-09-28 17:55 UTC, ChrisCollinsIBM approved these changes
Thanks for the updates!

2023-09-28 17:55 UTC, merged