Added workflow for PureStorage FlashArray
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #220
Opened 2024-02-20 05:01 UTC by unni-pure

Added workflow for PureStorage FlashArray

2024-02-22 17:48 UTC, ChrisCollinsIBM requested changes
Thanks for the submission, overall things look to be functional but I've added a few suggestions for improvements and cleanup.

If you want to skip the `<While>` to `<DoWhile>` suggestion I completely understand, but the indentation and cleanup of the sample variables would be appreciated.

Thanks!

2024-02-22 17:48 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashArray-workflow-parameter-values.xml
> +<Value name="apitoken"     value="c508e5e3-63d3-387b-33f1-ade0e58f0ca0" />
These should probably be blank rather than sample (possibly real) values.

The readme contains a note on what needs to go there so that's great.

2024-02-22 17:48 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashArray-workflow.xml
> +<CallEndpoint url="https://${/array}/api/${/apiversion}/alerts?filter=updated%3E${/5min_time}&amp;continuation_token=${/get_events/body/continuation_token}&amp;limit=10" method="GET" savePath="/get_e
Could you re-work this into a `<DoWhile>` loop instead? https://www.ibm.com/docs/en/dsm?topic=actions-dowhile - This would eliminate having to have 2 sets of `<CallEndpoint>` blocks? (one for the initial and another for the extra pages) along with all the other repeated code (headers, post event, etc)

Does the API work ok if you pass a blank continuation token? If so this would be pretty simple.

If not you could either build the queryString in an `<If>` statement saved to a variable, or just have 2 different `<CallEndpoint>` options within an `<If> <Else> </If>` block.

```suggestion
<DoWhile condition="/get_events/body/continuation_token != null">

<Log type="INFO" message="Reading next set of alerts if more than 10 alerts from the first API call" />

<If condition="/get_events/body/continuation_token != null">
    <!-- With Token -->
    <CallEndpoint url="https://${/array}/api/${/apiversion}/alerts?filter=updated%3E${/5min_time}&amp;continuation_token=${/get_events/body/continuation_token}&amp;limit=10" method="GET" savePath="/get_events">
        <RequestHeader name="Content-Type" value="application/json" />
        <RequestHeader name="x-auth-token" value="${/access_token}" />
    </CallEndpoint>
  <Else>
    <!-- Initial Call Without Token -->
    <CallEndpoint url="https://${/array}/api/${/apiversion}/alerts?filter=updated%3E${/5min_time}&amp;limit=10" method="GET" savePath="/get_events">
        <RequestHeader name="Content-Type" value="application/json" />
        <RequestHeader name="x-auth-token" value="${/access_token}" />
    </CallEndpoint>
</If>
```

Or something similar. This method repeats the RequestHeader tags so building the query String in an `<if>` statement likely makes more sense.

If that's not something you're interested in then no problem, the existing design works but I thought I'd offer some review feedback on structure.

2024-02-22 17:48 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashArray-workflow.xml
> +</Parameters>
For readability of the XML, could you please indent where tags are opened? (tabs or spaces) It's very helpful to troubleshoot and maintain that way.
```suggestion
<Workflow name="Dropbox Business" version="1.0" xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1">
<Parameters>
    <Parameter name="array" label="Array" required="true" />
    <Parameter name="apitoken" label="Access Token" required="true" secret="true" />
</Parameters>
```

It's especially helpful in the `<While>` loop and  `<CallEndpoint>` blocks.

2024-02-26 16:12 UTC, ChrisCollinsIBM approved these changes
Thanks for the update, looks good.

2024-02-26 16:47 UTC, unni-pure commented
Can this me merged to master branch now?

2024-02-26 18:25 UTC, merged