Workflow for Cyble Vision Integration #229
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #230
Opened 2024-03-25 09:36 UTC by cyble-dev

We have created a uREST API Protocol based Workflow for ingesting events from Cyble into QRadar. This workflow/integration will help user to seamlessly get events in their QRadar system.

2024-03-27 16:38 UTC, ChrisCollinsIBM requested changes
Thanks for the submission!

I've added a few CR comments here, some which you can ignore if you like, but the allowUntrusted one should be addressed as well as the requested Readme update.

2024-03-27 16:38 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/README.md
> +11. Do a full configuration deploy (__Deploy Changes -> Advanced -> Deploy Full Configuration__)
A full deploy is not needed to add a new log source, just a "Deploy Changes"

`11. Navigate to the __Admin__ tab. From the top bar choose __Deploy Changes__`

2024-03-27 16:38 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +        <CallEndpoint url="https://${/events_url}/apollo/api/v1/y/alerts" method="POST" savePath="/get_count">
A URL includes protocol (https://) the hostname, and the path. Calling the hostname "events_url" may cause some confusion or misconfigurations. You may want to consider renaming it to events_hostname but ultimately your choice as the current events_url value you're expecting is just the hostname element.

2024-03-27 16:38 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/README.md
> +| Fetch Since         | fetch_since    | _fetch_since_ is the number of previous days for which you wish to fetch events.                                            |
You may want to include "on the initial run" or similar wording in the description to make it clear what this value controls.

2024-03-27 16:38 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +            <Set path="/fromDate" value="${time() - /fetch_since * 24 * 60 * 60 * 1000}" />
If you look at other workflows, I think you'll see `<Initialize>` is usually used to set the initial poll timestamp date since Initialize only sets the value if it's empty. This removes the need for the `isFirstFetch` variable entirely and the `<If>` block here.

I'm sure this works fine as well but just wanted to mention it.

2024-03-27 16:38 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +            <SSLConfiguration allowUntrustedServerCertificate="true" />
Is there a reason you're specifically triggering this here? This `allowUntrustedServerCertificate="true"` shouldn't be in the workflow rather should be set in the Log Source itself when needed (there's a UI value to enable it). Setting this to true requires you to copy the certificate to your qradar machine. If the endpoint you're connecting to has a certificate issued by a public CA (Verisign, LetsEncrypt, etc) then this option isn't needed at all. "allowUntrusted" should only be used with self-signed certificates or those issued by a CA that hasn't been imported into the QRadar trust anchors.

2024-03-27 19:01 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +        <Parameter name="api_key" label="Api Key" required="true" />
Please make sure to add `secret = "true"` to the `<Parameter>` attribute to ensure the API key isn't logged in request/debug logging.

2024-03-28 13:25 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/README.md
> +11. Do a full configuration deploy (__Deploy Changes -> Advanced -> Deploy Full Configuration__)
Done

2024-03-28 13:25 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +        <CallEndpoint url="https://${/events_url}/apollo/api/v1/y/alerts" method="POST" savePath="/get_count">
Done

2024-03-28 13:26 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/README.md
> +| Fetch Since         | fetch_since    | _fetch_since_ is the number of previous days for which you wish to fetch events.                                            |
Fetch since is actually the number of previous days since when user wants to pull data.

2024-03-28 13:26 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +            <SSLConfiguration allowUntrustedServerCertificate="true" />
Removed it. Done.

2024-03-28 13:26 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/Cyble-Threat-Intel-Workflow.xml
> +        <Parameter name="api_key" label="Api Key" required="true" />
Done

2024-03-28 13:27 UTC, cyble-dev commented
Hello @ChrisCollinsIBM,
Thank you for your inputs and comments, I have implemented them and posted a comment as well.

Please move forward with the PR review and let me know if you need anything from my side.

Thanks.

2024-03-28 15:53 UTC, ChrisCollinsIBM commented on Community Developed/Cyble Threat Intel/README.md
> +| Fetch Since         | fetch_since    | _fetch_since_ is the number of previous days for which you wish to fetch events.                                            |
But it only applies to the very first time you run the workflow ever, correct? After that your `fromDate` and `toDate` move along in a sliding window.

This text here doesn't clearly explain that to a user in my opinion: 
`_fetch_since_ is the number of previous days for which you wish to fetch events.`

This pattern is used often on many workflows, and usually it's roughly explained in some context of "on first run" to make it clear.

2024-03-29 04:33 UTC, cyble-dev commented on Community Developed/Cyble Threat Intel/README.md
> +| Fetch Since         | fetch_since    | _fetch_since_ is the number of previous days for which you wish to fetch events.                                            |
Done. Modified the description as you suggested. Please proceed.

2024-04-01 04:33 UTC, cyble-dev commented
Hi @ChrisCollinsIBM,
I have made the changes you suggested. Please proceed.

2024-04-04 06:04 UTC, freddie400 commented
Hello @ChrisCollinsIBM,
We need this PR merged asap. Please proceed. Waiting for your response.

2024-04-04 07:19 UTC, cyble-dev commented
Hi @ChrisCollinsIBM,
We need this PR to be merged asap. Please review the PR, I have made the changes you suggested.

2024-04-04 11:03 UTC, ChrisCollinsIBM commented
Thanks for the update, if you can just at the DCO signoff I can get this merged for you.

Thank you.

2024-04-04 11:13 UTC, cyble-dev commented
Done @ChrisCollinsIBM.
Please proceed.

2024-04-04 20:46 UTC, ChrisCollinsIBM approved these changes
Thanks for the submission and making the requested updates!

2024-04-04 20:46 UTC, merged