Add a workflow for XPANSE. #236
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #238
Opened 2024-05-23 16:10 UTC by rislas83

For the QRadar Xpanse extension by Palo Alto Networks.
Signed-off-by: Roberto Islas Durand <rislasdurand@paloaltonetworks.com>

2024-07-23 18:06 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +					<PostEvent path="/data" source="api-${/xpanse_tenant}-alerts" />
Since the `source` here is `api-${/xpanse_tenant}-alerts` you should make a note in the readme that the log source identifier in the QRadar log source MUST match

eg: `api-mytenenat-alerts` if the xpanse_tenant is `mytenant`

We have an updated release of UREST coming soon where source can be omitted in PostEvent or PostEvents allowing the log source identifier to be any value..

2024-07-23 18:07 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-assets-workflow.xml
> +                <PostEvents path="/assetData/response/body/reply/assets_internet_exposure" source="api-${/xpanse_tenant}-assets" />
Since the source here is api-${/xpanse_tenant}-assets you should make a note in the readme that the log source identifier in the QRadar log source MUST match the resultant value here

eg: api-mytenenat-assets if the xpanse_tenant is mytenant

We have an updated release of UREST coming soon where source can be omitted in PostEvent or PostEvents allowing the log source identifier to be any value..

2024-07-23 18:27 UTC, ChrisCollinsIBM requested changes
Thanks for the submission!

I've offered a few suggestions for optimizations but ultimately it's up to you to take them into consideration now, later, or never.

The only thing that should be updated is the note relating to the required log source identifier base on the `source` used in the `<PostEvents>` elements to save our mutual customers some headaches.

Please have a look at the review items and resolve them as needed and we'll have a second look at it soon and get it merged.

Thanks!

2024-07-23 18:27 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow-parameter.xml
> +	<!-- Provide the number of days (i.e) from that time alerts will be fetched -->
This looks to be meant for controlling how far to go back in time on the very first run, you could consider mentioning that so it's not confused with how much data will come with each pull.

Also, if no default is provided here, some undesired behaviour may occur when multiplying a blank value on line 14 in the workflow. so you may want to consider populating a reasonable default (1 day, 7 days, whatever we normally be appropriate)

```<Set path="/historical_hours" value="${/historical_poll * 24}" />```

2024-07-23 18:27 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +					<PostEvent path="/data" source="api-${/xpanse_tenant}-alerts" />
Since the source here is api-${/xpanse_tenant}-alerts you should make a note in the readme that the log source identifier in the QRadar log source MUST match the resultant value here

eg: api-mytenenat-alerts if the xpanse_tenant is mytenant

We have an updated release of UREST coming soon (Schema v2.1) where source can be omitted in PostEvent or PostEvents allowing the log source identifier to be any value..

2024-07-23 18:27 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-assets-workflow.xml
> +                <PostEvents path="/assetData/response/body/reply/assets_internet_exposure" source="api-${/xpanse_tenant}-assets" />
Since the source here is api-${/xpanse_tenant}-assets you should make a note in the readme that the log source identifier in the QRadar log source MUST match the resultant value here

eg: api-mytenenat-assets if the xpanse_tenant is mytenant

We have an updated release of UREST coming soon (Schema v2.1) where source can be omitted in PostEvent or PostEvents allowing the log source identifier to be any value..

2024-07-23 18:27 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +		<Log type="INFO" message="Xpanse Events: historical time ${/historical_timestamp}" />
An info logger relating to an "initial run" part of the logic should probably be changed to `Debug`, or maybe moved to within the historical_poll `<ElsIf>` block to avoid confusion on timestamps.

2024-07-23 18:27 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +		<While condition="/counter &lt; /total">
Have 2 full copies of your polling logic (one for page 1, and for page 2..N) can be difficult to maintain, but can certainly be implemented like this and is done this way in a number of workflows.

If you're feeling creative and looking for a way to optimize the code, many workflows will use a `<DoWhile>` loop instead that's keyed off of something that can be controlled for the first page AND additional pages.

But this doesn't need to be changed, just offering some suggestions.

2024-07-23 18:58 UTC, rislas83 commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +					<PostEvent path="/data" source="api-${/xpanse_tenant}-alerts" />
The customers are accustomed to use the FQDN format for Xpanse integrations. This is clearly mentioned in the pdf of the documentation and in the README.md "Copy the Cortex Xpanse URL and remove “https://” if it is there at the start of the URL."
This is also mentioned in the docs shared with the customers of Xpanse. If we further explain that it should match with the format, it could confuse the customers.

2024-07-23 18:58 UTC, rislas83 commented on Community Developed/Xpanse/Xpanse-assets-workflow.xml
> +                <PostEvents path="/assetData/response/body/reply/assets_internet_exposure" source="api-${/xpanse_tenant}-assets" />
The customers are accustomed to use the FQDN format for Xpanse integrations. This is clearly mentioned in the pdf of the documentation and in the README.md "Copy the Cortex Xpanse URL and remove “https://” if it is there at the start of the URL."
This is also mentioned in the docs shared with the customers of Xpanse. If we further explain that it should match with the format, it could confuse the customers.

2024-07-23 18:59 UTC, rislas83 commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +		<Log type="INFO" message="Xpanse Events: historical time ${/historical_timestamp}" />
We can address this in the future. Thanks!

2024-07-23 18:59 UTC, rislas83 commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +		<While condition="/counter &lt; /total">
We can address this in the future. Thanks!

2024-07-23 19:00 UTC, rislas83 commented on Community Developed/Xpanse/Xpanse-alerts-workflow-parameter.xml
> +	<!-- Provide the number of days (i.e) from that time alerts will be fetched -->
Updating the file to the usual configuration.

2024-07-24 18:17 UTC, ChrisCollinsIBM commented on Community Developed/Xpanse/Xpanse-alerts-workflow.xml
> +					<PostEvent path="/data" source="api-${/xpanse_tenant}-alerts" />
Where I'm referring to is the "Log Source Identifier" field in the setup on the Protocol tab.

![image](https://github.com/user-attachments/assets/78d906c4-223a-47f9-a441-ffebaef7e973)

In the readme there is no mention made of what this field has to be set as, and with the `source` attribute being set (which is currently mandatory) the Log Source Identifier field MUST match whatever `source` the workflow sets.

So if the customer is familiar with `api-mytenenat-alerts` that's helpful, but you should probably mention in the setup what they need to provide for the Log Source Identifier as if it doesn't match all events will got to SIM-Generic and not the DSM you just configured so none of your events will be parsed.

I can merge this as-is for now, but you may want to review this and if you want to push a README.md update afterwards to clarify simply do another pull request.

2024-07-24 18:18 UTC, ChrisCollinsIBM approved these changes

2024-07-24 18:18 UTC, merged