New Log source for CyberArk Audit Service
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #249
Opened 2024-07-01 14:30 UTC by nitsan-tzur

2024-07-09 13:08 UTC, nitsan-tzur commented
Hi @ChrisCollinsIBM this is a new log source that integrates with CyberArk's Audit service. Could you please take a look to advance with the certification process. Thanks

2024-07-09 13:38 UTC, ChrisCollinsIBM requested changes
Thanks for the submission, the only mandatory changes are removing the `.DS_Store` artifacts, but it would be a good idea to add the tests as well as they are in the other CyberArk workflows.

2024-07-09 13:38 UTC, ChrisCollinsIBM commented on .DS_Store
Please remove all `.DS_Store` file system artifacts from PR

2024-07-09 13:38 UTC, ChrisCollinsIBM commented on Community Developed/.DS_Store
Please remove

2024-07-09 13:38 UTC, ChrisCollinsIBM commented on Community Developed/CyberArk Audit/.DS_Store
Please remove

2024-07-09 13:38 UTC, ChrisCollinsIBM commented on Community Developed/CyberArk Audit/CyberArk-Audit-Workflow.xml
> +</Workflow>
Usually it's good practice to add the TCP/DNS/SSL tests in case there are connectivity issues and someone wants to run the log source tests. It's not mandatory but it's a good idea.

Example: 

https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/master/Community%20Developed/CyberArk%20EPM/CyberArk-EPM-AggregatedPolicy-Workflow.xml#L170

https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/blob/master/IBM%20Verified/IBM%20Security%20QRadar%20EDR/QRadarEDR-Workflow.xml#L69

2024-07-12 15:15 UTC, nitsan-tzur commented on Community Developed/CyberArk Audit/CyberArk-Audit-Workflow.xml
> +</Workflow>
Added tests

2024-07-15 17:45 UTC, ChrisCollinsIBM approved these changes
Thanks for the updates @nitsan-tzur, greatly appreciated!

2024-07-15 17:46 UTC, merged