Pure Storage FlashBlade Workflow
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #262
Opened 2024-09-03 16:13 UTC by singhs72

We have added a workflow to integrate Pure Storage FlashBlade log sources with IBM QRadar. This workflow and its associated parameter file are designed to pull the desired alerts from Pure Storage FlashBlade.

2024-09-18 14:10 UTC, ChrisCollinsIBM requested changes
Thanks for the submission, I've flagged a few items for review so please have a look and address or resolve any of the issue as needed.

Thanks!

2024-09-18 14:10 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +      <Set path="/apiversion" value="${/get_apiversion/body/versions[/apiarraycount]}" />
It appears that the setting of `/apiarraycount` and `/apiversion` are swapped and are setting the value from the other from callEndpoint response.

```suggestion
      <Set path="/apiversion" value="${count(/get_apiversion/body/versions) - 1}" />
      <Set path="/apiarraycount" value="${/get_apiversion/body/versions[/apiarraycount]}" />
```

This might be as intended but worth following up on.

2024-09-18 14:10 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +        <Log type="INFO" message="Prepare URL to read next set of alerts if more than 10 alerts from the first API call" />
Logger mentions 10 alerts but the query has `limit=50`, the same on line 40 as well.

Whichever is intended it would be good if they matched.

2024-09-18 14:10 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +         <Log type="INFO" message="Valid alers present, posting alert to QRadar" />
```suggestion
         <Log type="INFO" message="Valid alerts present, posting alert to QRadar" />
```

2024-09-18 14:10 UTC, ChrisCollinsIBM commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +      <TCPConnectionTest host="${/array}" />
DNS and SSL tests are often helpful also, but not required, and HTTPConnectionThroughProxy may also be useful if Proxies are expected.

```
    <Tests>
        <DNSResolutionTest host="${/array}"/>
        <TCPConnectionTest host="${/array}"/>
        <SSLHandshakeTest host="${/array}"/>
        <HTTPConnectionThroughProxyTest url ="${/array}"/>
    </Tests>
```

2024-09-20 05:46 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +      <Set path="/apiversion" value="${/get_apiversion/body/versions[/apiarraycount]}" />
Thank you @ChrisCollinsIBM  for following up on this. However, this behavior is consistent with the product's intended functionality.

2024-09-20 05:48 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +      <TCPConnectionTest host="${/array}" />
Thank you @ChrisCollinsIBM for your suggestion. This would be customizable as per the User's requirement.

2024-09-20 06:11 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow-parameter-values.xml
> +<WorkflowParameterValues xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/WorkflowParameterValues/V1">
Thank you @ChrisCollinsIBM for your feedback. I have addressed the requested changes and re-submitted the updated code for review.

2024-09-20 06:12 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +<Workflow xmlns="http://qradar.ibm.com/UniversalCloudRESTAPI/Workflow/V1" name="PureStorage FlashBlade" version="1.0">
Thank you @ChrisCollinsIBM for your feedback. I have addressed the requested changes and re-submitted the updated code for review

2024-09-20 06:12 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +        <Log type="INFO" message="Prepare URL to read next set of alerts if more than 10 alerts from the first API call" />
Thank you @ChrisCollinsIBM for your feedback. I have addressed the requested changes and re-submitted the updated code for review

2024-09-20 06:12 UTC, singhs72 commented on Community Developed/PureStorage/PureStorage-FlashBlade-workflow.xml
> +         <Log type="INFO" message="Valid alers present, posting alert to QRadar" />
Thank you @ChrisCollinsIBM for your feedback. I have addressed the requested changes and re-submitted the updated code for review

2024-09-25 06:26 UTC, singhs72 commented
> Thanks for the submission, I've flagged a few items for review so please have a look and address or resolve any of the issue as needed.
> 
> Thanks!

Hi @ChrisCollinsIBM , As all the suggestions/feedback has been addressed, shall I go ahead  resolve the conversations?

2024-09-25 18:31 UTC, ChrisCollinsIBM approved these changes

2024-09-25 18:31 UTC, merged

2024-09-25 18:31 UTC, ChrisCollinsIBM commented
Thanks for submission and for addressing the CR feedback.

We look forward to seeing more submissions!