Add a workflow for GitLab audit logs
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #265
Opened 2024-09-12 13:49 UTC by michal0000000

### Description

Polls GitLab API every minute and retrieves events based on the configuration

### Event Types Supported by the workflow:

- Instance audit events (gitlab.com only)
- All group audit events (gitlab.com and self-hosted)
- All project audit events (gitlab.com and self-hosted)

### Parameters you will need:

- `apiHost` - hostname of your Gitlab instance
- `accessToken` - Personal Access Token with admin privileges
- `logType` - One of the following: `instance`,`groups`,`projects`
- `objectId` - Only used when `log_type` is `groups` or `projects`, represents the ID

### Example Output
https://ibb.co/LdxXYZC

2024-09-18 15:50 UTC, ChrisCollinsIBM requested changes
Thanks for the submission!

The readme looks great and everything in the code is nicely laid out, paging is handled too which is great.

There's an issue though around timestamps and query windows I included some detail on though that definitely needs to be addressed to ensure all data is captured and nothing is missing. Have a look at that comment and let me know if that all makes sense or if you need more details (or if I misread what's happening)

Thanks!

2024-09-18 15:50 UTC, ChrisCollinsIBM commented on Community Developed/GitLab/gitlab.xml
> +                <PostEvent path="/event" source="${/apiHost}"/>
Since you're already in a ForEach loop here, this is a good place to capture the timestamp from the event and save it for later. 

For a workflow like this you'll need to save the MAX timestamp you saw from the events if they're not in order in the response or the timestamp of the last event if they are in order. 

You'll need this to use as the `/sinceTimestamp` value for everything after the first run as currently it looks like it's on a fixed `1 minute ago` cycle which will result in missed events if the system is patched, services restarted, etc.

Often a timestamp is set as a variable and initialized with a default value for first run `initialize` vs `set` and then the value is populated via observed data after that.

As this workflow stands right there would be an almost guaranteed issue with missing events if the user didn't configured a 1 Minute recurrence, and even then if queries were off by portions of a second, service restarts, etc., data would be missing.

2024-10-20 08:19 UTC, michal0000000 commented
Any updates on this ?

2024-10-21 13:13 UTC, ChrisCollinsIBM commented
> Any updates on this ?

Hi @michal0000000, have you addressed the issue I highlighted in the review around the timestamp?

https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/pull/265#discussion_r1765314070

It's showing unresolved still and I don't see any new commits, so if you have made an update maybe it didn't push, and if you'd like to discuss I'm happy to assist.

2024-10-22 06:31 UTC, michal0000000 commented
I marked your comment as resolved. The commit addressing the issue is [f817d93922329747d5faab3aa465b6d8115dc0e2 ](https://github.com/IBM/IBM-QRadar-Universal-Cloud-REST-API/commit/f817d93922329747d5faab3aa465b6d8115dc0e2)

2024-10-22 12:02 UTC, ChrisCollinsIBM approved these changes

2024-10-22 12:06 UTC, merged