Add a Workflow for FireEye HX #87
IBM/IBM-QRadar-Universal-Cloud-REST-API pull request #91
Opened 2022-02-09 22:03 UTC by M-Shabrawy

2022-05-11 18:17 UTC, ChrisCollinsIBM requested changes
Thank for the submission. Overall it's very detailed and looks great.

I've added a few questions and things that I think need addressing, so if you could have a look at those that would be great.

Thanks for the submission!

2022-05-11 18:17 UTC, ChrisCollinsIBM commented on FireEye HX/README.md
> +-   -  Alert Groups: Lists all alert_groups
Can you provide some context on what the second set of workflow files is for?

Without knowing the product it's unclear where there's an "Alerts" workflow and an "Alert Groups" workflow.

2022-10-25 19:54 UTC, ChrisCollinsIBM commented
Changes have been requested prior to merging this workflow, please let me know if you have any questions or require any assistance.

Thanks!

2022-11-08 07:37 UTC, M-Shabrawy commented on FireEye HX/README.md
> +-   -  Alert Groups: Lists all alert_groups
HX API Contains 2 Endpoints for alerts, Alerts and Alert Groups.

Alerts endpoint will fetch a list of alerts from the systems based on search query.

Alert Groups will fetch aggregated alerts based on grouping filed criteria and search query.

2022-11-08 07:39 UTC, M-Shabrawy commented on FireEye HX/FireEye-HX-Alert_Groups-Workflow.xml
> +		<Parameter name="hx_port" label="Port" value="443" required="true" />
HX is offered in 2 flavors, On-prem Controller and Cloud  Controller

On-prem uses port 3000
Cloud uses port 443

2022-11-08 07:40 UTC, M-Shabrawy commented on FireEye HX/FireEye-HX-Alert_Groups-Workflow.xml
> +            <SSLConfiguration allowUntrustedServerCertificate="true" />
HX is offered in 2 flavors, On-prem Controller and Cloud Controller

So this will depend on deployment type

2024-07-24 18:24 UTC, ChrisCollinsIBM commented
Closing due to inactivity.

2024-07-24 18:24 UTC, closed without merging